{% set name = "ptflops" %}
{% set version = "0.7.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 84e437a3ccad1bb050c14c599a76555b345533287767da87758e38c9101a40a7

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pytorch
test:
  imports:
    - ptflops
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/sovrasov/flops-counter.pytorch
  summary: This tool is designed to compute the theoretical amount of multiply-add operations in neural networks.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cnpcshangbo
